name: Publish Docker servers

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker servers to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: szerr/drops

      - name: Build and push latest Docker servers
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: szerr/drops:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push version Docker servers
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: szerr/drops:${{ steps.get_version.outputs.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
